"""Create Activity & Art_type

Revision ID: afa1e847bf48
Revises: 6512332f4480
Create Date: 2024-09-29 17:12:56.780350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'afa1e847bf48'
down_revision: Union[str, None] = '6512332f4480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'activity', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('Name', sa.String(length=512), nullable=False, unique=True),
        sa.Column('TimeDescription', sa.String(length=512), nullable=False),
        sa.Column('Location', sa.String(length=512), nullable=False),
        sa.Column('WorkHours', sa.Integer(), nullable=False),
        sa.Column('WorkForce', sa.Integer(), nullable=False),
        sa.Column('WorkForceBalance', sa.Integer(), nullable=False),
        sa.Column('Description', sa.String(length=1024)),
        sa.Column('art_type_id',
                  sa.Integer(),
                  nullable=False,
                  foreign_key='art_type.id'), sa.PrimaryKeyConstraint('id'))
    op.create_table('art_type', sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('Name', sa.String(length=512), nullable=False),
                    sa.PrimaryKeyConstraint('id'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('art_type')
    op.drop_table('activity')
    # ### end Alembic commands ###
